apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-ui

spec:
  securityContext:
    runAsNonRoot: false
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app:  pacman-ui
  template:
    metadata:
      labels:
        app:  pacman-ui
    spec:
      containers:
      - image:  aelchin/pacman:1.1
        name: pacman-ui
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: true
