apiVersion: v1
kind: Service
metadata:
  name: pacman-ui
spec:
  externalIPs:
  - 192.168.0.86
  ports:
  - nodePort: 31955
    port: 8080
    protocol: TCP
  selector:
     app: pacman-ui
   
    
  
    
