apiVersion: v1
kind: Service
metadata:
  name: pacman-ui
spec:
  ports:
  - nodePort: 31955
  protocol: TCP
      targetPort: 8080
    selector:
      app: pacman-ui
  - port: 8080
    targetPort: 8000
  selector:
    app: pacman-ui
    externalIPs:
    - 192.168.0.86
    
